### ISSUE TITLE
TODO list as of Aug 30

### ISSUE THREAD

**Issue by odunbar** [CliMA/RandomFeatures.jl#1]
Code-base
Clima repo consistency: [Tom]
- [x] bors, 
- [x] codecov, 
- [ ] buildkite, 
- [x] Documenter, (Ollie)
- [x] climaformat,

Code additons
- [x] Docstrings - Ollie
- [x] refactor to remove `hyper sampler` 'get_optimize...'/`set_optimize...` which are not needed (external to the package)
- [ ] decide if we should store "feature_sample" within RF or whether we should just have it returned from the sampler. 
- [x]  RF "cost" for hyperparameter optimization (external in examples)
- [ ]  RF "cost" for hyperparameter optimization (in src?)
- [ ] Diagnostics such as LOO errors / training error  / test error - Tom
- [x] vector valued RF

Performance
- [x] Acceleration of linear solves using better packages or parallelism

Examples
- [x] 1d->1d training of hyperparameters
- [x] nd->1d training of hyperparameters
- [x] nd->md training of hyperparameters

**Comment by odunbar** [comment]
Slight issue updates today

**Comment by tsj5** [comment]
Reopening, since merging #3 auto-closed this by mistake (#3 only addresses part of the list)

**Comment by odunbar** [comment]
No intention of completing the rest of these tasks. therefore closing
